version: '3.9'

services:
  mongos:
    build: .
    restart: unless-stopped
    command: mongos --bind_ip localhost,mongos --keyFile /data/mongo_keyfile --configdb cfgReplicaSet/mongocfg:27019
    ports:
      - 27017:27017
  mongocfg:
    build: .
    restart: unless-stopped
    command: --replSet cfgReplicaSet --configsvr --bind_ip localhost,mongocfg --keyFile /data/mongo_keyfile
    ports:
      - 27019:27019
  mongo1:
    build: .
    restart: unless-stopped
    command: --shardsvr --replSet shardReplicaSet1 --bind_ip localhost,mongo1 --keyFile /data/mongo_keyfile
    volumes:
      - ./mongo_data1:/data/db
      # - ./mongo_keyfile:/data/mongo_keyfile
  mongo2:
    build: .
    restart: unless-stopped
    command: --shardsvr --replSet shardReplicaSet1 --bind_ip localhost,mongo2 --keyFile /data/mongo_keyfile
    volumes:
      - ./mongo_data2:/data/db
      # - ./mongo_keyfile:/data/mongo_keyfile
  mongo3:
    build: .
    restart: unless-stopped
    command: --shardsvr --replSet shardReplicaSet2 --bind_ip localhost,mongo3 --keyFile /data/mongo_keyfile
    volumes:
      - ./mongo_data3:/data/db
      # - ./mongo_keyfile:/data/mongo_keyfile
  mongo4:
    build: .
    restart: unless-stopped
    command: --shardsvr --replSet shardReplicaSet2 --bind_ip localhost,mongo4 --keyFile /data/mongo_keyfile
    volumes:
      - ./mongo_data4:/data/db
  jupyter:
    build: ./jupyter/
    ports: 
      - 8888:8888
    volumes:
      - ./jupyter/notebooks/:/notebooks/